version: '3.0'

services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - homenet
    restart: on-failure
  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      homenet:
        aliases:
          - postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

networks:
  homenet:
    attachable: true
    driver: 'bridge'
    ipam:
      config:
        - subnet: 10.10.1.0/24
          ip_range: 10.10.1.0/24
          gateway: 10.10.1.1

volumes:
  postgres-data:
